/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.36
 * Generated at: 2020-10-22 09:53:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.frame;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/study/springstudy/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Webpage/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1597715631274L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>header</title>\r\n");
      out.write("<!-- 전체 css -->\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\tli{list-style: none;}\r\n");
      out.write("\tbody, html {\r\n");
      out.write("\theight:100%; margin:0px; padding:0px;\r\n");
      out.write("\tfont-family: 'Times New Roman', serif;\r\n");
      out.write("}\r\n");
      out.write("\ta { text-decoration: none ; color: black;}\r\n");
      out.write("</style>\r\n");
      out.write("<!-- 왼 사이드바 -->\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t#s_sidebar {float:left; background-color: gray; position: fixed; width: 250px; height:100%;}\r\n");
      out.write("\t#s_sidebar ul ul {margin:2px; padding:2px; position:relative; text-align:center;}\r\n");
      out.write("\t#s_sidebar ul li li {width:200px; height: 30px; line-height: 30px;}\r\n");
      out.write("\t#s_sidebar ul ul li:hover {background: darkgray;}\r\n");
      out.write("\t#s_sidebar ul ul li:hover ul{display:block;}\r\n");
      out.write("\t#s_sidebar ul ul li a {width:200px; height: 30px; line-height: 30px}\r\n");
      out.write("\t#s_sidebar ul ul ul {display: none; position:absolute; left:205px; top:0px; background-color: gray}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction reviewList_go(f){\r\n");
      out.write("\t\tf.action=\"reviewList.do\";\r\n");
      out.write("\t\tf.submit();\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction qnaList_go(f){\r\n");
      out.write("\t\tf.action=\"qnaList.do\";\r\n");
      out.write("\t\tf.submit();\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction noticeList_go(f){\r\n");
      out.write("\t\tf.action=\"noticeList.do\";\r\n");
      out.write("\t\tf.submit();\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction cart_go(f){\r\n");
      out.write("\t\tf.action=\"cartList.do\";\r\n");
      out.write("\t\tf.submit();\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction login_go(f){\r\n");
      out.write("\t\tf.action=\"login.do\";\r\n");
      out.write("\t\tf.submit();\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- 왼쪽메뉴바 -->\t\r\n");
      out.write("\t<nav id =\"sidebar\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id = \"s_sidebar\" >\t\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t<div id=\"title\" >\r\n");
      out.write("\t\t<h1 style=\"Font-size:40px; text-align: center; \"><a href=\"home.do\">가나다라</a></h1>\r\n");
      out.write("\t\t<br><br>\r\n");
      out.write("\t\t\t<div id=\"main_gnb\">\r\n");
      out.write("\t\t\t\t<li class=\"m_bar\"><a href=\"cart.do\">장바구니</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"m_bar\"><a href=\"#\">마이페이지</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"m_bar\"><a href=\"login.do\">로그인</a></li>\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<br><br><br><br><br>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t<li>TOP\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li>OUTER\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"productList.do\">s menu1</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"productList.do\">s menu2</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"productList.do\">s menu3</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li>JACKET\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">s menu1</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">s menu2</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">s menu3</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li>SHIRTS\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">s menu1</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">s menu2</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">s menu3</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<li>BOTTOM\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li>JEANS\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">s menu1</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">s menu2</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">s menu3</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li>SLACKS\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">s menu1</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">s menu2</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">s menu3</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li>SHORTS\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">s menu1</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">s menu2</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">s menu3</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<li>ACCESSORY\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li>SHOES\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">s menu1</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">s menu2</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">s menu3</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li>BAGS\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">s menu1</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">s menu2</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">s menu3</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li>ACCESSORY\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">ring</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">necklace</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">watch</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<br><br><br><br><br>\t\r\n");
      out.write("\t\t\t<div class= \"other\">\r\n");
      out.write("\t\t\t\t<li><a href=\"qnaList.do\">QnA</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"noticeList.do\">공지사항</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"reviewList.do\">후기</a></li>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<form>\r\n");
      out.write("\t\t\t<fieldset style=\"width:150px;\">\r\n");
      out.write("\t\t\t<legend>검색</legend>\r\n");
      out.write("\t\t\t<input id=\"keyword\" name=\"keyword\" fw-filter=\"\" fw-label=\"검색어\" fw-msg=\"\" class=\"inputTypeText\" placeholder=\"\" onmousedown=\"SEARCH_BANNER.clickSearchForm(this)\" value=\"\" type=\"text\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"searchbtn\" onclick=\"SEARCH_BANNER.submitSearchBanner(this); return false;\"><i class=\"xi-search\" aria-hidden=\"true\"></i></div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</fieldset>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
