/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.36
 * Generated at: 2020-10-21 10:03:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class product_005fdetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>제품상세화면</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t.info_wrapper { padding:100px; width:100%; height:80%; padding-left:400px;}\r\n");
      out.write("\t.m_pic{ width:400px; height:600px;}\r\n");
      out.write("\t.s_pics {padding:10px; }\r\n");
      out.write("\t.s_pics img{ width:80px; height:120px;}\r\n");
      out.write("\t.s_pics fieldset{ width:340px; height:130px; }\r\n");
      out.write("\t.d_pics img{width: 800px; height: 800px; margin:50px;}\r\n");
      out.write("</style>\r\n");
      out.write("<style>\r\n");
      out.write("\t.detail{position:relative; left: 700px; bottom:700px;}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction buy() {\r\n");
      out.write("\t\tif(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login=='ok'}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("){\r\n");
      out.write("\t\t\tlocation.href = \"\"\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t  alert(\"로그인 하세요\");\r\n");
      out.write("\t\t  location.href = \"\"\r\n");
      out.write("\t\t}\r\n");
      out.write("\tfunction add_cart() {\r\n");
      out.write("\t\tif(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login=='ok'}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("){\r\n");
      out.write("\t\t\tlocation.href = \"?idx=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t  alert(\"로그인 하세요\");\r\n");
      out.write("\t\t  location.href = \"\"\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../frame/header.jsp", out, false);
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 상세내용 -->\r\n");
      out.write("<div>\r\n");
      out.write("<!-- 이미지 -->\r\n");
      out.write("<div class=info_wrapper >\r\n");
      out.write("\t<img class= m_pic alt=\"My Image\" src=\"../resources/images/맨투맨.jpeg\"> <!-- ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.p_image_l }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" -->\r\n");
      out.write("\t\t<div class= s_pics>\r\n");
      out.write("\t\t\t<fieldset>\r\n");
      out.write("\t\t\t<legend>함께할 코디</legend>\r\n");
      out.write("\t\t\t<a href=\"#\"><img src=\"../resources/images/맨투맨.jpeg\" alt=\"My Image\" ></a>\r\n");
      out.write("\t\t\t<a href=\"#\"><img src=\"../resources/images/맨투맨.jpeg\" alt=\"My Image\" ></a>\r\n");
      out.write("\t\t\t<a href=\"#\"><img src=\"../resources/images/맨투맨.jpeg\" alt=\"My Image\" ></a>\r\n");
      out.write("\t\t\t<a href=\"#\"><img src=\"../resources/images/맨투맨.jpeg\" alt=\"My Image\" ></a>\r\n");
      out.write("\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t\t<!-- 기본정보 -->\r\n");
      out.write("<div class=\"detail\">\r\n");
      out.write("<table style=\"border:0px;  text-align: left;\" >\r\n");
      out.write("\t<tbody>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>\r\n");
      out.write("\t\t\t\t<span style=\"font-size:12px;color:#000000;\">상품명</span> \r\n");
      out.write("\t\t\t</th>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<span style=\"font-size:12px;color:#000000;\">반팔 티셔츠 5color</span> <!-- ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.p_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" -->\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>\r\n");
      out.write("\t\t\t\t<span style=\"font-size:12px;color:#000000;\">가격</span> \r\n");
      out.write("\t\t\t</th>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<span style=\"font-size:12px;color:#000000;\">₩ 19,000</span> <!-- <fmt:formatNumber value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.p_price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" pattern=\"#,##0\" />원 -->\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</tbody>\r\n");
      out.write("</table>\r\n");
      out.write("<!-- 품목선택 -->\r\n");
      out.write("<table>\r\n");
      out.write("\t<tbody>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>Color</th>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<select>\r\n");
      out.write("\t\t\t\t\t<option value=\"*\" selected link_image> [필수] 옵션을 선택해주세요 </option>\r\n");
      out.write("\t\t\t\t\t<option value=\"**\" disabled link_image>----------------------------</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"black\" link_image>블랙</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"white\" link_image>화이트</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"charcol\" link_image>차콜</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"navy\" link_image>네이비</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"wine\" link_image>와인</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>사이즈</th>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<select>\r\n");
      out.write("\t\t\t\t\t<option value=\"*\" selected link_image> [필수] 옵션을 선택해주세요 </option>\r\n");
      out.write("\t\t\t\t\t<option value=\"**\" disabled link_image>----------------------------</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"small\" link_image>small</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"medium\" link_image>medium</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"large\" link_image>large</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"2\" align=\"center\">\r\n");
      out.write("\t\t\t\t<button onclick=\"buy()\">구매하기</button>\r\n");
      out.write("\t\t\t\t<button onclick=\"add_cart()\">장바구니</button>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</tbody>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<hr>\r\n");
      out.write("\r\n");
      out.write("<!-- 제품 상세 사진 및 설명 -->\r\n");
      out.write("\t<div class=d_pics>\r\n");
      out.write("\t<p align=\"center\">한 여름을 제외하고 모든 계절에 착용 가능한 블레이져 </p>\r\n");
      out.write("\t<p align=\"center\"><br></p>\r\n");
      out.write("\t<p align=\"center\">어쩌고 저쩌고 어쩌고 저쩌고 어쩌고 저쩌고 어쩌고 저쩌고</p>\r\n");
      out.write("\t<p align=\"center\"><br></p>\r\n");
      out.write("\t<p align=\"center\">살꺼 말꺼 사지마 살꺼야? 아냐 사지마 저리가 </p>\r\n");
      out.write("\t<p align=\"center\"><br></p>\r\n");
      out.write("\t<p align=\"center\">이걸 왜 사는거야 바보야? 어쩌고 저쩌고 블라블라블라브라</p>\r\n");
      out.write("\t<p align=\"center\"><br></p>\r\n");
      out.write("\t<p align=\"center\"><br></p>\r\n");
      out.write("\t<p align=\"center\"><br></p>\r\n");
      out.write("\t<p align=\"center\"><img src=\"../resources/images/맨투맨.jpeg\" alt=\"My Image\" ></p>\r\n");
      out.write("\t<p align=\"center\"><br></p>\r\n");
      out.write("\t<p align=\"center\"><br></p>\r\n");
      out.write("\t<p align=\"center\"><br></p>\r\n");
      out.write("\t<p align=\"center\"><img src=\"../resources/images/맨투맨.jpeg\" alt=\"My Image\" ></p>\r\n");
      out.write("\t<p align=\"center\"><br></p>\r\n");
      out.write("\t<p align=\"center\"><br></p>\r\n");
      out.write("\t<p align=\"center\"><br></p>\r\n");
      out.write("\t<p align=\"center\"><img src=\"../resources/images/맨투맨.jpeg\" alt=\"My Image\" ></p>\r\n");
      out.write("\t<p align=\"center\"><br></p>\r\n");
      out.write("\t<p align=\"center\"><br></p>\r\n");
      out.write("\t<p align=\"center\"><br></p>\r\n");
      out.write("\t<p align=\"center\"><img src=\"../resources/images/맨투맨.jpeg\" alt=\"My Image\" ></p>\r\n");
      out.write("\t<p align=\"center\"><br></p>\r\n");
      out.write("\t<p align=\"center\"><br></p>\r\n");
      out.write("\t<p align=\"center\"><br></p>\r\n");
      out.write("\t<p align=\"center\"><img src=\"../resources/images/맨투맨.jpeg\" alt=\"My Image\" ></p>\r\n");
      out.write("\t<p align=\"center\"><br></p>\r\n");
      out.write("\t<p align=\"center\"><br></p>\r\n");
      out.write("\t<p align=\"center\"><br></p>\r\n");
      out.write("\t<p align=\"center\"><img src=\"../resources/images/맨투맨.jpeg\" alt=\"My Image\" ></p>\r\n");
      out.write("\t<p align=\"center\"><br></p>\r\n");
      out.write("\t<p align=\"center\"><br></p>\r\n");
      out.write("\t<p align=\"center\"><br></p>\r\n");
      out.write("\t<p align=\"center\"><img src=\"../resources/images/맨투맨.jpeg\" alt=\"My Image\" ></p>\r\n");
      out.write("\t<p align=\"center\"><br></p>\r\n");
      out.write("\t<p align=\"center\"><br></p>\r\n");
      out.write("\t<p align=\"center\"><br></p>\r\n");
      out.write("\t<p align=\"center\"><img src=\"../resources/images/맨투맨.jpeg\" alt=\"My Image\" ></p>\r\n");
      out.write("\t<p align=\"center\"><br></p>\r\n");
      out.write("\t<p align=\"center\"><br></p>\r\n");
      out.write("\t<p align=\"center\"><br></p>\r\n");
      out.write("\t<p align=\"center\"><img src=\"../resources/images/맨투맨.jpeg\" alt=\"My Image\" ></p>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 제품 설명 ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.p_content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("-->\r\n");
      out.write("<div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../frame/footer.jsp", out, false);
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
